title: "mitra usaha tani"
email: wowthemesnet@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Yudianto
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-4V5KXHQRJ2

# Authors
authors:
  Yudianto:
    name: Yudianto
    display_name: Yudianto
    avatar: 'assets/images/sal.png'
    email: wowthemesnet@gmail.com
    web: https://linktr.ee/yudiant0
    twitter: https://twitter.com/wowthemesnet
    description: "Yudianto, penulis aktif di Budidayatani dan Mitrausahatani.com, memiliki hobi di bidang pertanian. Ia sering menulis artikel terkait teknik budidaya tanaman dan usaha tani, berkontribusi untuk mendukung pertanian yang berkelanjutan dan inovatif."
    
# Social
social:
  facebook: https://www.facebook.com/Mitrausahatanikita
  twitter: https://twitter.com/mitratanikita
  instagram: https://www.instagram.com/mitrautani
  linkedin: https://www.linkedin.com/company/mitrausahatani
  pinterest: https://id.pinterest.com/mitrausahatani/
  

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives

# Include media directory
include:
  - 'media'
